version: '3'
services:
  fiapd:
    depends_on:
     - fiapd-db
    image: mouflonjp/fiapd
    ports:
     - "8080:8080"
     - "8443:8443"
    environment:
      POSTGRESQL_CONNECTION_STRING: jdbc:postgresql://fiapd-db/fiapstorage2
    networks:
     - fiapd-network
  fiapd-db:
    image: mouflonjp/fiapd-db
    ports:
     - "5432:5432"
    networks:
      fiapd-network:
        aliases:
         - fiapd-db
networks: 
  fiapd-network:
    driver: bridge